-- ============================================================
-- FIX: applications table RLS
-- Error: "new row violates row-level security policy for table applications"
-- Run this in: Supabase Dashboard → SQL Editor → Run
-- ============================================================

-- 1. Make sure the table exists
CREATE TABLE IF NOT EXISTS public.applications (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id     BIGINT      REFERENCES public.jobs(id) ON DELETE CASCADE,
  name       TEXT,
  email      TEXT,
  phone      TEXT,
  message    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- 3. Drop any old conflicting policies
DROP POLICY IF EXISTS "applications_insert_public" ON public.applications;
DROP POLICY IF EXISTS "applications_insert_anon"   ON public.applications;
DROP POLICY IF EXISTS "applications_select_admins" ON public.applications;
DROP POLICY IF EXISTS "applications_select_own"    ON public.applications;

-- 4. Anyone (logged in or not) can submit an application
CREATE POLICY "applications_insert_public" ON public.applications
  FOR INSERT WITH CHECK (true);

-- 5. Only approved admins and superadmin can read applications
CREATE POLICY "applications_select_admins" ON public.applications
  FOR SELECT USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );
