-- ============================================================
-- SAFE MIGRATION — adds missing columns to the existing jobs
-- table WITHOUT dropping it (does NOT delete existing jobs).
-- Run this in Supabase Dashboard → SQL Editor if the jobs
-- table already exists but is missing some columns.
-- ============================================================

-- 1. Add missing columns (IF NOT EXISTS — safe to run multiple times)
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS specialty     TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS salary        TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS tasks         TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS requirements  TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS benefits      TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS posted_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS company_logo  TEXT DEFAULT '🏥';

-- 2. Make sure RLS is on
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- 3. Re-create policies (DROP first so they are idempotent)
DROP POLICY IF EXISTS "jobs_select_public"   ON public.jobs;
DROP POLICY IF EXISTS "jobs_insert_admins"   ON public.jobs;
DROP POLICY IF EXISTS "jobs_update_admins"   ON public.jobs;
DROP POLICY IF EXISTS "jobs_delete_admins"   ON public.jobs;

-- Anyone can read jobs
CREATE POLICY "jobs_select_public" ON public.jobs
  FOR SELECT USING (true);

-- Approved admins and superadmin can insert
CREATE POLICY "jobs_insert_admins" ON public.jobs
  FOR INSERT WITH CHECK (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- Approved admins and superadmin can update
CREATE POLICY "jobs_update_admins" ON public.jobs
  FOR UPDATE USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- Approved admins and superadmin can delete
CREATE POLICY "jobs_delete_admins" ON public.jobs
  FOR DELETE USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- 4. Applications table (safe to run even if it already exists)
CREATE TABLE IF NOT EXISTS public.applications (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id     BIGINT      REFERENCES public.jobs(id) ON DELETE CASCADE,
  name       TEXT,
  email      TEXT,
  phone      TEXT,
  message    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "applications_insert_public" ON public.applications;
DROP POLICY IF EXISTS "applications_select_admins" ON public.applications;

CREATE POLICY "applications_insert_public" ON public.applications
  FOR INSERT WITH CHECK (true);

CREATE POLICY "applications_select_admins" ON public.applications
  FOR SELECT USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- 5. After running this SQL, go to:
--    Supabase Dashboard → Settings → API → click "Reload schema"
--    This forces the PostgREST schema cache to pick up the new columns.
