-- ============================================================
-- SAFE MIGRATION — adds ALL required columns to the existing
-- jobs table WITHOUT dropping it (does NOT delete existing jobs).
-- Safe to run multiple times. Run in:
--   Supabase Dashboard → SQL Editor → Run
-- Then: Settings → API → Reload schema
-- ============================================================

-- 1. Core text columns
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS title         TEXT NOT NULL DEFAULT '';
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS company       TEXT NOT NULL DEFAULT '';
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS city          TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS facility_type TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS job_type      TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS description   TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS company_logo  TEXT DEFAULT '🏥';
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS specialty     TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS salary        TEXT;

-- 2. Array columns
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS tasks         TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS requirements  TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS benefits      TEXT[] DEFAULT ARRAY[]::TEXT[];

-- 3. Relational / timestamp columns
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS posted_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 4. Make sure RLS is enabled
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- 5. Re-create RLS policies (idempotent)
DROP POLICY IF EXISTS "jobs_select_public" ON public.jobs;
DROP POLICY IF EXISTS "jobs_insert_admins" ON public.jobs;
DROP POLICY IF EXISTS "jobs_update_admins" ON public.jobs;
DROP POLICY IF EXISTS "jobs_delete_admins" ON public.jobs;

CREATE POLICY "jobs_select_public" ON public.jobs
  FOR SELECT USING (true);

CREATE POLICY "jobs_insert_admins" ON public.jobs
  FOR INSERT WITH CHECK (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

CREATE POLICY "jobs_update_admins" ON public.jobs
  FOR UPDATE USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

CREATE POLICY "jobs_delete_admins" ON public.jobs
  FOR DELETE USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- 6. Applications table
CREATE TABLE IF NOT EXISTS public.applications (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id     BIGINT      REFERENCES public.jobs(id) ON DELETE CASCADE,
  name       TEXT,
  email      TEXT,
  phone      TEXT,
  message    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "applications_insert_public" ON public.applications;
DROP POLICY IF EXISTS "applications_select_admins" ON public.applications;

CREATE POLICY "applications_insert_public" ON public.applications
  FOR INSERT WITH CHECK (true);

CREATE POLICY "applications_select_admins" ON public.applications
  FOR SELECT USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- After running: Supabase Dashboard → Settings → API → Reload schema


-- 2. Make sure RLS is on
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- 3. Re-create policies (DROP first so they are idempotent)
DROP POLICY IF EXISTS "jobs_select_public"   ON public.jobs;
DROP POLICY IF EXISTS "jobs_insert_admins"   ON public.jobs;
DROP POLICY IF EXISTS "jobs_update_admins"   ON public.jobs;
DROP POLICY IF EXISTS "jobs_delete_admins"   ON public.jobs;

-- Anyone can read jobs
CREATE POLICY "jobs_select_public" ON public.jobs
  FOR SELECT USING (true);

-- Approved admins and superadmin can insert
CREATE POLICY "jobs_insert_admins" ON public.jobs
  FOR INSERT WITH CHECK (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- Approved admins and superadmin can update
CREATE POLICY "jobs_update_admins" ON public.jobs
  FOR UPDATE USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- Approved admins and superadmin can delete
CREATE POLICY "jobs_delete_admins" ON public.jobs
  FOR DELETE USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- 4. Applications table (safe to run even if it already exists)
CREATE TABLE IF NOT EXISTS public.applications (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id     BIGINT      REFERENCES public.jobs(id) ON DELETE CASCADE,
  name       TEXT,
  email      TEXT,
  phone      TEXT,
  message    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "applications_insert_public" ON public.applications;
DROP POLICY IF EXISTS "applications_select_admins" ON public.applications;

CREATE POLICY "applications_insert_public" ON public.applications
  FOR INSERT WITH CHECK (true);

CREATE POLICY "applications_select_admins" ON public.applications
  FOR SELECT USING (
    (auth.jwt() ->> 'email') = 'kramabid1@gmail.com'
    OR
    EXISTS (
      SELECT 1 FROM public.users
       WHERE id     = auth.uid()
         AND role   IN ('admin', 'superadmin')
         AND status = 'approved'
    )
  );

-- 5. After running this SQL, go to:
--    Supabase Dashboard → Settings → API → click "Reload schema"
--    This forces the PostgREST schema cache to pick up the new columns.
